# Минимальная версия инфраструктуры на базе
# OpenSearch - хранилище логов и метрик
# OpenSearch Dashboards - отрисовка логов
# Fluent Bit - служба сбора логов
# Envoy - прокси
# Keycloak - сервер идентификации

# Адреса:
# Приложение доступно по http://localhost:8090 (envoy прокси)
# Панели мониторинга http://localhost:5601 (opensearch dashboards, kibana)
# Управление пользователями http://localhost:8081 (keycloak)

#version: "3"

services:

  app:
    container_name: numismatic-app
    build:
        context: .
        dockerfile: Dockerfile-app
    depends_on:
      - fluent-bit
      - envoy
#    volumes:
#      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      # используемый драйвер логгирования
      driver: "fluentd"
      options:
        # куда посылать лог-сообщения, необходимо чтобы адрес
        # совпадал с настройками плагина forward
        fluentd-address: localhost:24224
        # теги используются для маршрутизации лог-сообщений, тема
        # маршрутизации будет рассмотрена ниже
        tag: app.logs

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:3.0.3-amd64
    ports:
      # необходимо открыть порты, которые используются плагином forward
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=admin
    volumes:
      - ./volumes/fluent-bit-etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./volumes/fluent-bit-etc/parsers.conf:/fluent-bit/etc/parsers.conf:ro

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.13.0
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=adm-Password0
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch

  envoy:
    container_name: envoy-service
    image: envoyproxy/envoy:v1.30.1  # Use the official Envoy proxy image
    volumes:
      - ./volumes/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro  # Mount your Envoy configuration file
    #      - ./envoy/certs:/etc/envoy/certs  # Mount your TLS certificates
    ports:
      - "15001:15001"
      - "8090:8090"
    depends_on:
      - keycloak

  keycloak:
    container_name: keycloak-service
#    image: keycloak/keycloak:24.0.3-0
    build:
       context: .
       dockerfile: Dockerfile-keycloak # пришлось сделать Dockerfile, потому что с ключем --import-realm keycloak не хотел делать импорт при старте и не запускался
    ports:
      - "8081:8080"
#    volumes:
    #  - ./volumes/keycloak/import:/opt/keycloak/data/import:ro
    #      - ./keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    #      - ./keycloak/certs/keycloak.jks:/etc/x509/https/keystore  # Mount your Keycloak keystore
#    environment:
##      KEYCLOAK_USER: otus
##      KEYCLOAK_PASSWORD: otus
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    command:
#      - start-dev
      #      - --features admin-fine-grained-authz
#      - --hostname-port=8081
#      - --import-realm

volumes:
  opensearch-data:
